# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94a5ae3784936a209b7b515b1e94615156fa608c6cc8b319e6151be76ff5f8ff894eda3bd4ff5be784d9e713710252f932b38cb435ecd8bdbcfe12e1bbf786e3

test:
  secret_key_base: 49f4f53b806e51e5ab941d702903b5d4666174ed9d7d9a1ae884a5072f57fba59bcc8acf88e0e286b16033e1ee5960a90aae3a247d9bfda084710bb7fc7862d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
